# version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    # image mariadb_42: the _42 suffix is to avoid name conflicts with official mariadb image
    image: mariadb_42
    # Load variables from .env file
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    # healthcheck to ensure mariadb is ready before wordpress tries to connect
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    # image wordpress_42: the _42 suffix is to avoid name conflicts with official wordpress image
    image: wordpress_42
    # Load variables from .env file
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    # Wait for mariadb healthcheck to pass
    depends_on:
      mariadb:
          condition: service_healthy
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    # image nginx_42: the _42 suffix is to avoid name conflicts with official nginx image
    image: nginx_42
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      # Nginx needs access to WP files to serve static assets (images, css)
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always

  # =================   BONUS: Redis   ================= #
  redis:
    container_name: redis
    build: ./requirements/redis
    image: redis_42
    networks:
      - inception
    restart: always

  # =================    BONUS: ftp    ================= #
  ftp:
    container_name: ftp
    build: ./requirements/ftp
    image: ftp_42
    env_file:
      - .env
    volumes:
      # Mount the SAME volume as WordPress
      - wordpress_data:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    restart: always

  # =================   BONUS: website  ================= #
  website:
    container_name: website
    build: ./requirements/website
    image: website_42
    # ports:
    #   - "8080:80"  # Map Host 8080 to Container 80
    networks:
      - inception
    restart: always

  # =================  BONUS: Adminer  ================= #
  adminer:
    container_name: adminer
    build: ./requirements/adminer
    image: adminer_42
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
  # ==================================================== #

# Define the network
networks:
  inception:
    driver: bridge

# Define the volumes
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # ABSOLUTE PATH TO YOUR HOST MACHINE FOLDER
      device: /home/anemet/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # ABSOLUTE PATH TO YOUR HOST MACHINE FOLDER
      device: /home/anemet/data/wordpress
